#pragma once
#include "Task.h"
#include "ITaskPart.h"
#include "TaskAssigned.h"
#include "TaskComment.h"
#include "TaskStatus.h"
#include "Team.h"
#include "Session.h"
#include "Employee.h"
#include "Report.h"

#include "Repository.h"
#include "RepositoryList.h"
#include "TaskRepository.h"
#include "TeamRepository.h"
#include "EmployeeRepository.h"
#include "SessionRepository.h"
#include "ReportRepository.h"

#include "Connection.h"
